version: '3.8'

services:
  backend:
    image: chathoy-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: chathoy-backend
    restart: always
    volumes:
      - ./signaling-server:/backend
      - /backend/node_modules
