name: chathoy

on:
  push:
      branches: ["main"]
  pull_request:
      branches: ["main"]
      paths-ignore:
          - 'README.md'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ngyngcphu/chathoy_version_ci-cd
  IMAGE_TAG: 0.1.0
  CD_USERNAME: ngyngcphu

permissions:
  packages: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
        -   name: Checkout
            uses: actions/checkout@v3
        
        -   name: Setup Docker buildx
            uses: docker/setup-buildx-action@v2

        -   name: Log into registry ${{ env.REGISTRY }}
            uses: docker/login-action@v2
            with:
                registry: ${{ env.REGISTRY }}
                username: ${{ env.CD_USERNAME }}
                password: ${{ secrets.GITHUB_TOKEN }}

        -   name: Build and push
            uses: docker/build-push-action@v3
            with:
                context: .
                push: true
                tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
        -   name: Deploy
            uses: appleboy/ssh-action@master
            with:
                host: ${{ secrets.VPS_HOST }}
                port: ${{ secrets.VPS_PORT }}
                username: ${{ secrets.VPS_USERNAME }}
                password: ${{ secrets.VPS_PASSWORD }}
                
                script: |
                  export CR_PAT=${{ secrets.GITHUB_TOKEN }}
                  echo $CR_PAT | docker login ${{ env.REGISTRY }} -u ${{ env.CD_USERNAME }} --password-stdin
                  docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

                  mkdir -p ChatHoy-server
                  cd ChatHoy-server
                  curl https://raw.githubusercontent.com/ngyngcphu/chathoy_version_ci-cd/main/docker-compose.yml -o docker-compose.yml
                  docker compose stop chathoy_version_ci-cd
                  docker compose rm -f chathoy_version_ci-cd
                  docker compose up -d chathoy_version_ci-cd
                  docker logout ${{ env.REGISTRY }}